### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by JusticeRage**
This pull request includes the changes suggested in #25's review.

### CODE REVIEW

**Comment by Tethik** [comment]
You don't need to make a new PR after every change. It would be easier for us to review if all the changes were in the same thread.

Anyway, looks good to me still. Ping @eschaefer

**Comment by JusticeRage** [comment]
Sorry, I'm not used to making PRs. I didn't know how to update the previous one.

**Comment by Tethik** [comment]
That's ok. It should be as easy as committing and pushing on the same branch as your original PR. Github will automatically detect the changes.

**Comment by JusticeRage** [comment]
Thanks, I'll remember that.

**Pull request merged**
