### PR TITLE
Adding inclusiveness language

### PR DESCRIPTION
**Pull request by mlowdi**
Adds English inclusivity wording through `activist_p3` and `hacker_p3` and subsequently re-numbers the `hacker_p3` from master to `hacker_p4`. Layout updates follow this.

DE, FR, GR translations missing but stubs are in place ("TODO: translate").

### CODE REVIEW

**Comment by Tethik** [comment]
I'm not sure the translation stubs for non-english localizations are a good idea. Maybe better to leave them unchanged or empty until we have someone who can translate the new parts.

**Comment by mlowdi** [comment]
OK, that's an easy fix (and yeah, thinking about it that kind of thing *is* prone to cause confusion.) What's the content generator's behavior when you have empty/non-existing translation strings? Does it throw an error or just not fill/create the paragraphs?

**Comment by Tethik** [comment]
Empty, e.g.
```yml
activist_p2: ""
```
Will result in an empty string in that place.

However if the key doesnt exist in the fr.yml it will grab the string in default language (english) and render that instead.

Even though mixing in English paragraphs might look bad, it might also get contributors more readily wanting to fix it ;)

**Comment by mlowdi** [comment]
Here we go. No stubs, just empty strings.

**Pull request merged**
